run-title: "TripletMnist"

paths:
  save: "Models/2"
  load: "Models/2/model.10-0.0036.h5"

train:
  lr: 0.001
  optim: "Nadam"

  epochs: 100
  batch-size: 500

  loss: "semi-hard-triplet-loss"
  alpha: 0.2

  lr_reduce_factor: 0.5
  patience: 5
  min_lr: 1.0e-5

  resume: False

data:
  imsize: 28 
  imchannel: 1
  num_classes: 10

  val_split: 0.1

