run-title: "TripletMnist"

paths:
  save: "Models/14"
  load: ""

train:
  lr: 0.001
  optim: "Nadam"

  epochs: 100
  batch-size: 400
  k_batch: 40

  loss: "semi-hard-triplet-loss"
  alpha: 0.2
  beta: 0.1
  scale: 64
  reg_lambda: 0.01

  lr_reduce_factor: 0.5
  patience: 5
  min_lr: 1.0e-5

  shuffle: False
  resume: False

data:
  imsize: 28 
  imchannel: 1
  num_classes: 10

  samples_per_id: 6000
  val_split: 0.1